title: Charles Kanter # your name (or website title) here
logo: "/images/Headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  Columbia Engineering MS in Operations Research graduate with a talent for bridging the gap between
  technical concepts and diverse audiences.
  <br><br>
  
  Skilled in data science, machine learning, and deep learning, with professional experience in financial risk analytics, 
  alternative asset management, and management consulting. Passionate about the intersection of finance, technology,
  and driving data-powered solutions.
  <br><br>
  
  <a href="https://www.linkedin.com/in/charleskanter/">View My LinkedIn Profile</a> 
  <br><br>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-7903X46DS8 # your Google Analytics tracking ID here
